
NAME = ft_display_file
FLAGS = -Wall -Werror -Wextra
SRCS = main.c ft_display_file.c
BINARY = main.o ft_display_file.o

.PHONY: all
all :
	gcc $(FLAGS) -o $(NAME) $(SRCS)

.PHONY: clean
clean :
	/bin/rm -f $(BINARY)
.PHONY: fclean
fclean :
	/bin/rm -f $(NAME)
